apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: default
resources:
  - ../../services/nginx-svc
  - ../../services/node-svc
  - ../../services/redis-svc
  - networkpolicy.yaml
  - ingress.yaml
images:
  - name: nginx-svc
    newName: ghcr.io/leeon3345/nginx-service-v2
    newTag: 303b4ab358df2b16a769bfcc01bd1050478e66d4
  - name: node-svc
    newName: ghcr.io/leeon3345/node-service-v2
    newTag: 303b4ab358df2b16a769bfcc01bd1050478e66d4