apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: minikube-deploy-test
  namespace: argocd
  labels:
    app.kubernetes.io/managed-by: grad-deploy
    grad-deploy/project: "minikube_deploy_test"
spec:
  project: minikube-deploy-test-project
  source:
    repoURL: https://github.com/leeon3345/minikube_deploy_test
    targetRevision: HEAD
    path: k8s/projects/minikube_deploy_test/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers: [/spec/replicas]