apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: redis-svc
  namespace: default
  labels:
    app: redis-svc
    app.kubernetes.io/managed-by: grad-deploy
spec:
  serviceName: redis-svc
  selector:
    matchLabels:
      app: redis-svc
  template:
    metadata:
      labels:
        app: redis-svc
    spec:
      securityContext:
        runAsUser: 999
      containers:
        - name: redis-svc
          image: "redis:7-alpine"
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "200m"
              memory: "256Mi"
          envFrom:
            - configMapRef:
                name: redis-svc-config
            - secretRef:
                name: redis-svc-secret
                optional: true
          startupProbe:
            exec:
              command:
              - "redis-cli"
              - "ping"
            failureThreshold: 10
            periodSeconds: 5
          livenessProbe:
            exec:
              command:
              - "redis-cli"
              - "ping"
            failureThreshold: 3
            periodSeconds: 30
          readinessProbe:
            exec:
              command:
              - "redis-cli"
              - "ping"
            failureThreshold: 3
            periodSeconds: 10
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "standard"
        resources:
          requests:
            storage: 10Gi